# ----------------------------------------------------------------------------#
#                                                                             #
#                               Sudoku config                                 #
#                                                                             #
#                                  by Nikl                                    #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
langFile: "default"

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "35:4"
    # display name of the button
    displayName: "&3Sudoku"
    # lore of the button
    lore:
    - ""
    - "&1The famous logic game"
  gameButtons:
    saveStats:
      materialData: "159:3"
      displayName: "&c&lMixed difficulty"
      lore:
      - ""
      - "&cClimb up the &ltop list"
      - "&aGood luck!"
      - ""
      - "&1Cost: &420"
      slot: 22
      cost: 20
      token: 1
      money: 30
      # if true the best score of this button is saved
      saveStats: true
  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    saveStats:
      materialData: "159:11"
      displayName: "&cTop list"
      lore:
      - ""
      - "&cMixed difficulty &1Top List"
      slot: 31
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '              Top List'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %score% for the highest score of the player
      skullLore:
      - ''
      - '&6Rank:&1 %rank%'
      - '&6Wins:&1 %wins%'


rules:
  # enable/disable sound
  playSounds: true


# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false

items:
  # the grid items are divided into 3 categories
  #   cover items fill not-jet set slots
  #   tip items are used for the already given numbers at the beginning of the game
  #   number items are used for the player input

  # the grid is divided in 9 3x3 fields like this

  #    1   2   3
  #
  #    4   5   6
  #
  #    7   8   9

  # for each 3x3 field the items can be customized
  grid:
    '1':
      cover:
        materialData: "160:11"
        displayName: "&1"
      tip:
        materialData: "159:11"
        displayName: "&1&l&n%value%"
      number:
        materialData: "35:11"
        displayName: "&1%value%"
    '2':
      cover:
        materialData: "160"
        displayName: "&f"
      tip:
        materialData: "159"
        displayName: "&f&l&n%value%"
      number:
        materialData: "35"
        displayName: "&f%value%"
    '3':
      cover:
        materialData: "160:11"
        displayName: "&1"
      tip:
        materialData: "159:11"
        displayName: "&1&l&n%value%"
      number:
        materialData: "35:11"
        displayName: "&1%value%"
    '4':
      cover:
        materialData: "160"
        displayName: "&f"
      tip:
        materialData: "159"
        displayName: "&f&l&n%value%"
      number:
        materialData: "35"
        displayName: "&f%value%"
    '5':
      cover:
        materialData: "160:11"
        displayName: "&1"
      tip:
        materialData: "159:11"
        displayName: "&1&l&n%value%"
      number:
        materialData: "35:11"
        displayName: "&1%value%"
    '6':
      cover:
        materialData: "160"
        displayName: "&f"
      tip:
        materialData: "159"
        displayName: "&f&l&n%value%"
      number:
        materialData: "35"
        displayName: "&f%value%"
    '7':
      cover:
        materialData: "160:11"
        displayName: "&1"
      tip:
        materialData: "159:11"
        displayName: "&1&l&n%value%"
      number:
        materialData: "35:11"
        displayName: "&1%value%"
    '8':
      cover:
        materialData: "160"
        displayName: "&f"
      tip:
        materialData: "159"
        displayName: "&f&l&n%value%"
      number:
        materialData: "35"
        displayName: "&f%value%"
    '9':
      cover:
        materialData: "160:11"
        displayName: "&1"
      tip:
        materialData: "159:11"
        displayName: "&1&l&n%value%"
      number:
        materialData: "35:11"
        displayName: "&1%value%"
